springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: se.magnus.microservices.composite.product
  pathsToMatch: /**

api:
  common:
    version: 1.0.0
    title: Sample API

server.port: 17000
app:
  product-service:
    host: localhost
    port: 17001
  recommendation-service:
    host: localhost
    port: 17002
  review-service:
    host: localhost
    port: 17003
logging:
  level:
    root: INFO
    se.magnus.microservices: DEBUG

---
spring.config.activate.on-profile: docker

server.port: 8080

app:
  product-service:
    host: product
    port: 8080
  recommendation-service:
    host: recommendation
    port: 8080
  review-service:
    host: review
    port: 8080